### ISSUE TITLE
[x] ERROR create: verify: mail not found

### ISSUE THREAD

**Issue by Taurage** [d4c5d1e0/webtoons#2]
It's throwing this error all the time...

**Comment by Taurage** [comment]
seems like tidal.lol isn't working properly :(

**Comment by d4c5d1e0** [comment]
As I stated in the README they aren't sending emails anymore, I don't doubt there's some way to make them send the mails again but I don't care that much about this project to fix it

**Comment by Taurage** [comment]
I think they are sending the emails, but the api you've used don't work properly, if you try to get the inbox from the api, there is no response I think

**Comment by Tainted06** [comment]
You need to use your own domain or other emails, they've banned the domain tidal.lol. You can still use the tidal api, but you have to use your own domain.
