### ISSUE TITLE
Unable to Read Episode 1

### ISSUE THREAD

**Issue by samocodes** [d4c5d1e0/webtoons#4]
The code is encountering an issue where it fails to read episode 1. Upon inspecting the JSON response received, it is evident that the first response did not complete successfully. This issue prevents the code from accessing the content of episode 1.

**Expected Result:**
The code should successfully read episode 1 without any errors or incomplete responses.

**Actual Result:**
The code encounters an issue where the first JSON response is incomplete, leading to the failure to read episode 1.

**Additional Information:**
- JSON responses received during execution:
  - First response: `{"message":{"type":"response","service":"com.naver.webtoon","version":"0.0.1","result":{"progressType":"NONE"}}}`
  - Second response: `{"message":{"type":"response","service":"com.naver.webtoon","version":"0.0.1","result":{"progressType":"POPUP","pageUrl":"https://m.webtoons.com/app/promotion/read/en_discord_phase1_202305/progress%22%7D%7D%7D`
  - Third response: `{"message":{"type":"response","service":"com.naver.webtoon","version":"0.0.1","result":{"progressType":"POPUP","pageUrl":"https://m.webtoons.com/app/promotion/read/en_discord_phase1_202305/progress%22%7D%7D%7D`
  - Fourth response: `{"message":{"type":"response","service":"com.naver.webtoon","version":"0.0.1","result":{"progressType":"POPUP","pageUrl":"https://m.webtoons.com/app/promotion/read/en_discord_phase1_202305/progress%22%7D%7D%7D`

**Comment by sudo216** [comment]
The first response isn't suppose to give any popup's so its a normal response expected from the server to respond

**Comment by samocodes** [comment]
> The first response isn't suppose to give any popup's so its a normal response expected from the server to respond

But somehow it's affecting to get nitro link.

**Comment by d4c5d1e0** [comment]
There are other factors that may be affecting the inability to receive nitro, but the reading part is not one of them

**Comment by samocodes** [comment]
> There are other factors that may be affecting the inability to receive nitro, but the reading part is not one of them

I tried  the tool last night, but I was unable to obtain the code till now. However, my friend managed to got it manually in just 10 minutes.

**Comment by d4c5d1e0** [comment]
I know that the tool isn't working currently and it doesn't matter, it's not a plug and play solution, feel free to play with and fix it :)
